Repository uprm-inso4116-2024-2025-s1/semester-project-SafeRUM, pull requests merged in 2024-10, with the labels that each got.

#249 Added boundaries to area of interest (In ReportMap)
  safe-rum/app/(tabs)/ReportMap.tsx
Labels: Location Management Team

#260 Reports Tab added
  safe-rum/app/(tabs)/Reports.tsx
Labels: Trust System Team, Milestone 2

#270 IntegrityError handling
  db/blueprints/auth.py
Labels: User Account & Sessions Team, Milestone 2

#279 Add priority reports and notifications
  .vscode/settings.json
  safe-rum/app/(tabs)/ReportViewing.tsx
  safe-rum/package-lock.json
  safe-rum/package.json
Labels: Trust System Team

#289 Custom callouts map and `Pin` component
  safe-rum/app/(tabs)/ReportMap.tsx
  safe-rum/components/Pin.tsx
Labels: Location Management Team, Completed

#288 Double the amount of dummy data for the database
  db/sql/insert_dummy_data_admins.sql
  db/sql/insert_dummy_data_alerts.sql
  db/sql/insert_dummy_data_reports.sql
  db/sql/insert_dummy_data_users.sql
Labels: Trust System Team, Completed, Milestone 2

#299 Report history
  safe-rum/app/(tabs)/ReportDeletion.tsx
Labels: Administrator Accounts & Sessions Team, Completed, Milestone 2

#301 Align Report Creation UI with Designed UI Specifications
  safe-rum/app/(tabs)/ReportCreation.tsx
  safe-rum/app/(tabs)/home.tsx
Labels: Enhancement, Trust System Team, Completed, Milestone 2

#293 Implement the report editing UI
  safe-rum/.prettierrc
  safe-rum/app/(tabs)/ReportViewing.tsx
  safe-rum/components/ViewReport.tsx
Labels: Question, Trust System Team, Completed

#302 Add report in a history for report deletion
  safe-rum/app/(tabs)/ReportDeletion.tsx
  safe-rum/app/(tabs)/home.tsx
  safe-rum/components/UserLogin.tsx
Labels: Administrator Accounts & Sessions Team, Completed, Milestone 2

#318 [Lecture Topic Task] Report Object Life Cycle
  safe-rum/app/(tabs)/ReportDeletion.tsx
  safe-rum/app/(tabs)/home.tsx
Labels: Administrator Accounts & Sessions Team, Completed, Milestone 2

#319 Implemented Dummy Logout and Inactivity Logout
  safe-rum/app/(tabs)/Session_Management.tsx
Labels: Administrator Accounts & Sessions Team, Completed, Milestone 2

#311 removed blueprints/auth.py
  db/app.py
  db/blueprints/auth.py
  db/blueprints/users.py
Labels: User Account & Sessions Team, TL Approved, Milestone 2

#313 Implemented Redirection System
  safe-rum/components/UserLogin.tsx
Labels: Administrator Accounts & Sessions Team, Completed, Milestone 2

#317 Applying changes.
  safe-rum/app/(tabs)/_layout.tsx
  safe-rum/app/(tabs)/home.tsx
  safe-rum/app/(tabs)/login.tsx
  safe-rum/app/(tabs)/userAuthScreen.tsx
  safe-rum/app/Profile.tsx
  safe-rum/app/ReportCreation.tsx
  safe-rum/app/ReportDeletion.tsx
  safe-rum/app/ReportViewing.tsx
  safe-rum/app/Reports.tsx
  safe-rum/app/Settings.tsx
  safe-rum/app/index.tsx
  safe-rum/components/UserLogin.tsx
  safe-rum/components/ViewReport.tsx
Labels: Administrator Accounts & Sessions Team, Completed, Milestone 2, Merge Conflict

#321 Conflict fix
  safe-rum/app/ReportDeletion.tsx
Labels: Administrator Accounts & Sessions Team, Completed, Milestone 2

#315 added modal that opens u hit the report button
  safe-rum/app/(tabs)/ReportMap.tsx
Labels: Completed

#327 230 implementation for admin calendar
  safe-rum/app/Calendar/Calendar.tsx
  safe-rum/app/Calendar/MonthlyView.tsx
  safe-rum/app/Calendar/YearlyView.tsx
  safe-rum/app/Profile.tsx
Labels: Administrator Accounts & Sessions Team, Completed, Milestone 2

#328 Implemnted Email Verification Dummy Code
  safe-rum/app/(tabs)/ReportMap.tsx
  safe-rum/app/Calendar/Calendar.tsx
  safe-rum/app/Calendar/MonthlyView.tsx
  safe-rum/app/Calendar/YearlyView.tsx
  safe-rum/app/Profile.tsx
Labels: Administrator Accounts & Sessions Team, Completed, Milestone 2
