Repository uprm-inso4116-2024-2025-s1/semester-project-SafeRUM, pull requests merged in 2024-11, with the labels that each got.

#347 [Lecture Topic Task] Refactor Settings.tsx add comments
  safe-rum1/app/Settings.tsx
Labels: Administrator Accounts & Sessions Team, TL Approved, Completed, Milestone 3

#357 Role based navigation and routing
  safe-rum1/app/(tabs)/_layout.tsx
  safe-rum1/app/(tabs)/home.tsx
  safe-rum1/app/(tabs)/login.tsx
  safe-rum1/app/Authentication.tsx
  safe-rum1/app/ReportCreation.tsx
  safe-rum1/app/ReportDeletion.tsx
  safe-rum1/app/admins/Profile.tsx
  safe-rum1/app/admins/ReportMap.tsx
  safe-rum1/app/admins/ReportViewing.tsx
  safe-rum1/app/admins/Session_Management.tsx
  safe-rum1/app/admins/_layout.tsx
  safe-rum1/app/index.tsx
  safe-rum1/app/users/Profile.tsx
  safe-rum1/app/users/Reports.tsx
  safe-rum1/app/users/Session_Management.tsx
  safe-rum1/app/users/_layout.tsx
  safe-rum1/components/Login.tsx
  safe-rum1/components/Signup.tsx
  safe-rum1/components/UserLogin.tsx
  safe-rum1/components/ViewReport.tsx
Labels: Enhancement, User Account & Sessions Team, TL Approved, Milestone 3

#395 Added notification alert on reports
  safe-rum1/app/users/Profile.tsx
Labels: Administrator Accounts & Sessions Team, Completed, Milestone 3

#397 Report Categories Updated
  safe-rum1/app/ReportCreation.tsx
Labels: Trust System Team, Completed

#394 CreateReport button connection to the create tab
  safe-rum1/app/users/Reports.tsx
Labels: Trust System Team, Merge Conflict

#404 Add role verification into admin routes
  backend/blueprints/users.py
  backend/firebase.py
Labels: User Account & Sessions Team, Completed, Milestone 3

#406 360 update colors on implemented app
  safe-rum1/app/Calendar/AddReportModal.tsx
  safe-rum1/app/Calendar/MonthlyView.tsx
  safe-rum1/app/Calendar/YearlyView.tsx
  safe-rum1/app/EditProfile.tsx
  safe-rum1/app/ReportCreation.tsx
  safe-rum1/app/ReportDeletion.tsx
  safe-rum1/app/Settings.tsx
  safe-rum1/app/admins/Profile.tsx
  safe-rum1/app/admins/ReportViewing.tsx
  safe-rum1/app/users/Profile.tsx
  safe-rum1/app/users/Reports.tsx
  safe-rum1/components/ViewReport.tsx
Labels: Trust System Team, Completed, Milestone 3

#399 Show users the report guidelines when they're going to submit a report
  safe-rum1/app/ReportCreation.tsx
  safe-rum1/app/ReportGuidelines.tsx
Labels: Trust System Team, Completed, Milestone 3

#398 Jjulianirizarry24/userstatusicon
  safe-rum1/app/admins/ReportMap.tsx
  safe-rum1/assets/images/green.jpg
  safe-rum1/assets/images/red.jpg
  safe-rum1/assets/images/yellow.jpg
  safe-rum1/package-lock.json
  safe-rum1/package.json
Labels: Location Management Team

#429 Help button added for Report Creation page following Open/Closed principle and Intention-revealing interfaces
  safe-rum1/app/ReportCreation.tsx
Labels: Trust System Team, Milestone 3

#430 App Guidelines button and implementation
  safe-rum1/app/AppGuidelines.tsx
  safe-rum1/app/Settings.tsx
Labels: Trust System Team, Milestone 3

#434 Refactor EditProfile code and created ProfileHeader component
  safe-rum1/app/EditProfile.tsx
  safe-rum1/app/ProfileHeader.tsx
Labels: Administrator Accounts & Sessions Team, Completed, Milestone 3

#435 Finished LLT for Intention Revealing Interface for Admins
  safe-rum1/app/admins/Profile.tsx
  safe-rum1/app/admins/_layout.tsx
Labels: Administrator Accounts & Sessions Team, Completed, Milestone 3

#446 Add assertions to report creation process
  safe-rum1/app/ReportCreation.tsx
Labels: Trust System Team, Completed, Milestone 3

#448 ReportCreation Refactoring to Comply with Multiple DDD Principles
  safe-rum1/app/ReportCreation.tsx
Labels: Trust System Team, Completed, Milestone 3

#455 Document Flask Endpoints Using Flask-Autodoc
  backend/app.py
  backend/blueprints/README.md
  backend/blueprints/admins.py
  backend/blueprints/alerts.py
  backend/blueprints/auth.py
  backend/blueprints/reports.py
  backend/blueprints/users.py
  backend/blueprints/verify.py
Labels: Approved, User Account & Sessions Team, TL Approved, Completed, Milestone 3

#456 created the session context and track if user is logged in or not
  safe-rum1/app/Settings.tsx
  safe-rum1/app/contexts/SessionContext.tsx
  safe-rum1/components/Login.tsx
Labels: Approved, Completed, Milestone 3
