Repository uprm-inso4116-2024-2025-s1/semester-project-SafeRUM, pull requests merged in 2024-09, with the labels that each got.

#166 Implement Report Creation UI
  safe-rum/app/(tabs)/home.tsx
Labels: Trust System Team, Milestone 1, Completed

#168 Save Changes Profile
  safe-rum/app/(tabs)/Profile.tsx
  safe-rum/app/EditProfile.tsx
Labels: Admin Account and Sessions Team, Milestone 1, Completed

#174 Implement Report Deletion UI
  safe-rum/app/(tabs)/ReportDeletion.tsx
Labels: Trust System Team

#175 Implementation Help button Color Guide
  safe-rum/app/(tabs)/ReportMap.tsx
  safe-rum/components/HelpButton.tsx
  safe-rum/tsconfig.json
Labels: Location Management Team
